### PR TITLE
update DB schema

### PR DESCRIPTION
**Pull request by dyuliu**
When we are using Orion, the logic we follow is that:

**step0:** we already have many datasets (one dataset is one signal) and pipelines;

**step1:** we create a new project say “NASA”;

**step2:** for a created project, we can run multiple different experiments. Each experiment will use the same pipeline running on different datasets. "Datarun" is the term used to describe the behavior of running a specific pipeline on a certain dataset. Thus, in one experiment, multiple dataruns would be generated.

**Therefore, I slightly changed the DB schema to fit this logic.**

In addition, there are two additional collections "Raw" and "Prediction", storing the time series data of every signal after aggregation and model's prediction results, respectively. These data will be used for visualization.

The example db could be found:
        curl -o nasa.tar.bz2 "http://dongyu.name/data/nasa"
	tar -xvf nasa.tar.bz2 && rm nasa.tar.bz2
	mongorestore --db nasa ./nasa/

**----------------------- important --------------------**
I did not push the changes on other files for dumping data with the new schema, as I change many unnecessary parts of the code for experimental use. 

I share my forked version of Orion with all the changes to Carles and Alex, where I mainly add a primitive called "data_dumper" to dump all required data to mongodb. But this could not be the optimal solution, as I have to add several ugly intermedia primitives to explicitly save some useful data to context variables, because I don't want to change any lines of the originally integrated primitives.

@csala and @AlexanderGeiger  Can you give suggestions on this so that we can find a better way to dump the required data?

### CODE REVIEW

**Comment by AlexanderGeiger** [comment]
Hi @dyuliu,

In my opinion the cleanest way would be to implement all the database interaction in orion/explorer.py. This way we don't need additional primitives. However, that means we have to get the aggregated raw values and the predictions out of the pipeline context. In order to do this, we can presumably use the intermediate output functionality, which was introduced to MLBlocks [here](https://github.com/HDI-Project/MLBlocks/pull/85).
However, MLBlocks does not seem to support multiple outputs by variable name. @csala is that correct?
My suggestion would be to add this functionality to MLBlocks. That way we could extract the necessary context variables based on their name while running the pipeline and store all the necessary information using only the Orion explorer. 
So I imagine something like this in the explorer:
```
# start datarun -> insert all information about datarun into database
...
events, y, y_hat = mlpipeline.predict(data, _output=["events", "y", "y_hat"])
...
# end datarun -> add events, y, y_hat to the datarun in the database
```
The only thing when developing new pipelines is to make sure that the relevant context variables are named accordingly inside the pipeline.

What do you think about this approach?

**Comment by dyuliu** [comment]
> Hi @dyuliu,
> 
> In my opinion the cleanest way would be to implement all the database interaction in orion/explorer.py. This way we don't need additional primitives. However, that means we have to get the aggregated raw values and the predictions out of the pipeline context. In order to do this, we can presumably use the intermediate output functionality, which was introduced to MLBlocks [here](https://github.com/HDI-Project/MLBlocks/pull/85).
> However, MLBlocks does not seem to support multiple outputs by variable name. @csala is that correct?
> My suggestion would be to add this functionality to MLBlocks. That way we could extract the necessary context variables based on their name while running the pipeline and store all the necessary information using only the Orion explorer.
> So I imagine something like this in the explorer:
> 
> ```
> # start datarun -> insert all information about datarun into database
> ...
> events, y, y_hat = mlpipeline.predict(data, _output=["events", "y", "y_hat"])
> ...
> # end datarun -> add events, y, y_hat to the datarun in the database
> ```
> 
> The only thing when developing new pipelines is to make sure that the relevant context variables are named accordingly inside the pipeline.
> 
> What do you think about this approach?

@AlexanderGeiger:
I agree. If MLBlock support dumping context variables out, that would be good.

**Comment by dyuliu** [comment]
@AlexanderGeiger:
I agree. If MLBlock support dumping context variables out, that would be good.

**Comment by csala** [comment]
I want to add several separated comments about this:

1. About the Experiments: at some point we discussed a slightly different schema, that would be as follows:
    * A Dataset is associated with a Satellite and has a collection of Signals
    * A Signal is associated with a single CSV file and has a start and a stop.
    * An Experiment is related to a Pipeline and a Dataset.
    * Dataruns are related to an Experiment and a Signal, which implicitly relates them to a Dataset and a Pipeline.

    For this, we should:
    * Rename the current Dataset to Signal.
    * Remove the satellite_id and signal_set fields from the Signal model.
    * Add another Dataset model that is parent to Signal and has the satellite_id field.
    * Create the Experiment model and make it related to Dataset and Pipeline.
    * Make the Dataruns related to the Experiment.
    * Remove the Datarun <-> Pipeline relationship (as it comes through the Experiment).

    Can we adapt the changes to this schema?

2. About Raw and Predictions: I am not sure about we wanting to store that information in the DB. At least not the one that comes from the anomaly detection pipeline.

    The reason is that the current LSTM based pipelines have both an aggregation pre--processing step and an LSTM regression, but this won't necessarily be like that for all the pipelines. We might have pipelines that do not perform either of those steps, or that perform them differently, with different output formats. For example, we might have a pre-processing step (e.g. some fft based featurization) that does not output an aggregated average but rather some other values that do not really represent the signal when plotted. Therefore, we cannot make the visualization infrastructure dependent on these two steps in the pipeline or we might find ourselves not being able to visualize the data the future if the pipelines that we are using do not have these steps.

    In any case, if data really needs to be stored in the database for visualization, I would simply create a separated aggregation process (it can be an MLBlocks pipeline that has only the aggregation step) that generates the data exactly as the visualization software expects, but I would make that unrelated to the anomaly detection pipeline. And I would not make the visualization dependent on any signal prediction step within the pipeline unless it is an optional feature that is active only for certain pipelines.

3. About pipeline intermediate outputs: Even though, as I explained above, I would not make the visualization depend on the pipeline outputs, we still might want to extract intermediate outputs from the pipeline in order to get more insight about what is going on. If this is necessary, extracting several intermediate outputs IS possible.

    In order to do this, instead of specifying the name of the variable that you want to output, you need to specify the name (or id) of the block that you want the output from, and the result will be the complete pipeline context at that point.

    For example, the equivalent to the snipped that @AlexanderGeiger put above would be:

    ```
    ctx = mlpipeline.predict(data, _output=-1)    # gets the context after the last block
    events = ctx['events']
    y_hat = ctx['y_hat']
    y = ctx['y']
    ```

4. About the Visualization <-> Orion interaction, in general: We need to make the visualization completely independent form the internal Orion implementation, and especially from the Anomaly Detection process. More specifically, what we need to do is to completely isolate the visualization from the DB and make them interact through an implementation agnostic API like a GRPC or Web API.

    This means that the Orion DB schema needs to be designed to store all the information needed for the visualization, but that the exact details about how that data is stored should not affect it, as far as the needed data is available.

    For this reason, instead of discussing this here, I think that it would be reasonable to restrict this PR to the DB schema change about the Dataset <> Signal <> Experiment structure, and open a new issue to specifically discuss the Visualization <> DB interaction.

**Comment by dyuliu** [comment]
@csala:

1. This is workable. Only one thing, that is, parent to Experiment, there should have a model called "Project" that contains multiple experiments.

2. Your concern on Raw is right and this can be easily separated out as one independent pipeline.  That is also what I am doing now. The problem lays in dumping the predictive results which is highly related to the anomaly detection pipeline. So the ideal solution is to make MLBlock support dump intermediate results.

3. This is good.

4. Currently, MTV actually does not directly interact with Orion as there is no such use scenario. Orion  is only used to dump events and some other information to MongoDB. MTV is a separated project, which only adds some additional information to the MongoDB and interacts with the MongoDB only. This means the connection between MTV and Orion currently is that they share the same DB schema in most cases.

 In the future, if Orion supports more advanced computations that need to be executed in real-time, we will consider creating a bridge between them though GRPC or web API.

**Comment by csala** [comment]
> 1. This is workable. Only one thing, that is, parent to Experiment, there should have a model called "Project" that contains multiple experiments.

Given the nature of MongoDB, I would only add this if there are other variables that need to be added to this Project model. If that's the case, go for it!

Otherwise, if this is only a way to group multiple Experiments together but not share any common variables, I would simply add a "project_id" field in the Experiment model and put there an Id for each project, but skip the creation of a full blown model for that.

> I also discuss with Alex, we both think we can still link datarun to signal level. But when users run a pipeline in a dataset, multiple dataruns will be produced where each datarun means the pipeline running on a signal contained in that dataset. These dataruns would be linked to this experiment.

I'm not sure if you mean something else, but I think that you are actually saying the same as me:

* A Dataset is related to several Signals, so the Signal model has a "dataset_id" field.
* An Experiment is related to a Dataset and a Pipeline, which means that it has both a "dataset_id" and a "pipeline_id" fields.
* A Datarun is related to an Experiment and a Signal, which means that it has an "experiment_id" and a "signal_id". But the Datarun is NOT related to a pipeline, because the relation comes through the Experiment.

Is this what you mean?

In any case, what we need to try to enforce is that there is only one path to relate two different collections, otherwise we might end up having inconsistent data.

> 2. Your concern on Raw is right and this can be easily separated out as one independent pipeline.  That is also what I am doing now. The problem lays in dumping the predictive results which is highly related to the anomaly detection pipeline.

The point here is that the predictions are very specific to this pipeline in particular, so my actual question is: Do we need to have this in the DB? And, more specifically, do we really want that level of insight in the visualization? Bear in mind that there could be the case where the regression is useful for the pipeline to find the anomalies, but that it might not be meaningful for the user that is looking at the results. So what I actually mean is that perhaps we should just ignore the fact that the pipeline has a regression within it and focus only on the raw data and the detected anomalies.

Also, if we still want this, what will happen when we don't have this because the pipeline does not have a regression? We need to make sure that the visualization does not depend on it.

> So the ideal solution is to make MLBlock support dump intermediate results.

Just to make sure that this is clear: MLBlocks already supports this, so we don't need to add anything to MLBlocks, just use it :-)

> 4. Currently, MTV actually does not directly interact with Orion as there is no such use scenario. Orion  is only used to dump events and some other information to MongoDB. MTV is a separated project, which only adds some additional information to the MongoDB and interacts with the MongoDB only. This means the connection between MTV and Orion currently is that they share the same DB schema in most cases.

That was the point, precisely: **MTV should not access the Orion Database directly**, but rather interact with it through a Web API that is part of Orion.

This way, only Orion depends on the DB Schema and only Orion needs to be adapted if we make any modification in the Database at any point.

**Pull request closed without merging**
